name: application_layer_http
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.2

dependencies:
  http: ^1.2.2
  json_annotation: ^4.9.0
  convert: any

dev_dependencies:
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  lints: ^4.0.0
  test: ^1.24.0
